// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// Rcpp_DrawS_LNIRT
List Rcpp_DrawS_LNIRT(const arma::vec& alpha0, const arma::vec& beta0, const arma::vec& guess0, const arma::vec& theta0, const arma::mat& Y);
RcppExport SEXP LNIRT_Rcpp_DrawS_LNIRT(SEXP alpha0SEXP, SEXP beta0SEXP, SEXP guess0SEXP, SEXP theta0SEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha0(alpha0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type guess0(guess0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta0(theta0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    __result = Rcpp::wrap(Rcpp_DrawS_LNIRT(alpha0, beta0, guess0, theta0, Y));
    return __result;
END_RCPP
}
// Rcpp_DrawZ_LNIRT
arma::mat Rcpp_DrawZ_LNIRT(const arma::vec& alpha0, const arma::vec& beta0, const arma::vec& theta0, const arma::mat& S, const arma::mat& D, const arma::mat& eta, const bool PNO);
RcppExport SEXP LNIRT_Rcpp_DrawZ_LNIRT(SEXP alpha0SEXP, SEXP beta0SEXP, SEXP theta0SEXP, SEXP SSEXP, SEXP DSEXP, SEXP etaSEXP, SEXP PNOSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec& >::type alpha0(alpha0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta0(theta0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const bool >::type PNO(PNOSEXP);
    __result = Rcpp::wrap(Rcpp_DrawZ_LNIRT(alpha0, beta0, theta0, S, D, eta, PNO));
    return __result;
END_RCPP
}
// Rcpp_DrawC_LNIRT
arma::fvec Rcpp_DrawC_LNIRT(const arma::mat& S, const arma::mat& Y);
RcppExport SEXP LNIRT_Rcpp_DrawC_LNIRT(SEXP SSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    __result = Rcpp::wrap(Rcpp_DrawC_LNIRT(S, Y));
    return __result;
END_RCPP
}
// rcpp_hello
List rcpp_hello();
RcppExport SEXP LNIRT_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpp_hello());
    return __result;
END_RCPP
}
