# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@export
Rcpp_DrawS_LNIRT <- function(alpha0, beta0, guess0, theta0, Y) {
    .Call('LNIRT_Rcpp_DrawS_LNIRT', PACKAGE = 'LNIRT', alpha0, beta0, guess0, theta0, Y)
}

#'@export
Rcpp_DrawZ_LNIRT <- function(alpha0, beta0, theta0, S, D, eta, PNO) {
    .Call('LNIRT_Rcpp_DrawZ_LNIRT', PACKAGE = 'LNIRT', alpha0, beta0, theta0, S, D, eta, PNO)
}

#'@export
Rcpp_DrawTheta_LNIRT <- function(alpha0, beta0, Z, mu, sigma) {
    .Call('LNIRT_Rcpp_DrawTheta_LNIRT', PACKAGE = 'LNIRT', alpha0, beta0, Z, mu, sigma)
}

#'@export
Rcpp_DrawZeta_LNIRT <- function(RT, phi, lambda, sigma2, mu, sigmaz) {
    .Call('LNIRT_Rcpp_DrawZeta_LNIRT', PACKAGE = 'LNIRT', RT, phi, lambda, sigma2, mu, sigmaz)
}

#'@export
Rcpp_DrawC_LNIRT <- function(S, Y) {
    .Call('LNIRT_Rcpp_DrawC_LNIRT', PACKAGE = 'LNIRT', S, Y)
}

#'@export
Rcpp_DrawBeta_LNIRT <- function(theta, alpha, Z, mu, sigma) {
    .Call('LNIRT_Rcpp_DrawBeta_LNIRT', PACKAGE = 'LNIRT', theta, alpha, Z, mu, sigma)
}

#'@export
Rcpp_DrawLambda_LNIRT <- function(RT, phi, zeta, sigma2, mu, sigmal) {
    .Call('LNIRT_Rcpp_DrawLambda_LNIRT', PACKAGE = 'LNIRT', RT, phi, zeta, sigma2, mu, sigmal)
}

#'@export
Rcpp_DrawAlpha_LNIRT <- function(theta, beta, Z, mu, sigma) {
    .Call('LNIRT_Rcpp_DrawAlpha_LNIRT', PACKAGE = 'LNIRT', theta, beta, Z, mu, sigma)
}

#'@export
Rcpp_DrawPhi_LNIRT <- function(RT, lambda, zeta, sigma2, mu, sigmal) {
    .Call('LNIRT_Rcpp_DrawPhi_LNIRT', PACKAGE = 'LNIRT', RT, lambda, zeta, sigma2, mu, sigmal)
}

#'@export
Rcpp_SampleS2_LNIRT <- function(RT, zeta, lambda, phi) {
    .Call('LNIRT_Rcpp_SampleS2_LNIRT', PACKAGE = 'LNIRT', RT, zeta, lambda, phi)
}

#'@export
Rcpp_SampleB_LNIRT <- function(Y, X, Sigma, B0, V0) {
    .Call('LNIRT_Rcpp_SampleB_LNIRT', PACKAGE = 'LNIRT', Y, X, Sigma, B0, V0)
}

#'@export
Rcpp_rwishart_LNIRT <- function(nu, V) {
    .Call('LNIRT_Rcpp_rwishart_LNIRT', PACKAGE = 'LNIRT', nu, V)
}

#'@export
rcpp_hello <- function() {
    .Call('LNIRT_rcpp_hello', PACKAGE = 'LNIRT')
}

