# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@export
Rcpp_Conditional <- function(kk, Mu, Sigma, Z) {
    .Call('LNIRT_Rcpp_Conditional', PACKAGE = 'LNIRT', kk, Mu, Sigma, Z)
}

#'@export
Rcpp_SimulateRT <- function(RT, zeta, lambda, phi, sigma2, DT) {
    .Call('LNIRT_Rcpp_SimulateRT', PACKAGE = 'LNIRT', RT, zeta, lambda, phi, sigma2, DT)
}

#'@export
Rcpp_SimulateY <- function(Y, theta, alpha0, beta0, guess0, D) {
    .Call('LNIRT_Rcpp_SimulateY', PACKAGE = 'LNIRT', Y, theta, alpha0, beta0, guess0, D)
}

#'@export
Rcpp_DrawZeta <- function(RT, phi, lambda, sigma2, mu, sigmaz) {
    .Call('LNIRT_Rcpp_DrawZeta', PACKAGE = 'LNIRT', RT, phi, lambda, sigma2, mu, sigmaz)
}

#'@export
Rcpp_SampleB <- function(Y, X, Sigma, B0, V0) {
    .Call('LNIRT_Rcpp_SampleB', PACKAGE = 'LNIRT', Y, X, Sigma, B0, V0)
}

#'@export
Rcpp_rwishart <- function(nu, V) {
    .Call('LNIRT_Rcpp_rwishart', PACKAGE = 'LNIRT', nu, V)
}

#'@export
Rcpp_DrawLambdaPhi_LNRT <- function(RT, theta, sigma2, muI, sigmaI, ingroup) {
    .Call('LNIRT_Rcpp_DrawLambdaPhi_LNRT', PACKAGE = 'LNIRT', RT, theta, sigma2, muI, sigmaI, ingroup)
}

#'@export
Rcpp_SampleS_LNRT <- function(RT, zeta, lambda, phi, ingroup) {
    .Call('LNIRT_Rcpp_SampleS_LNRT', PACKAGE = 'LNIRT', RT, zeta, lambda, phi, ingroup)
}

#'@export
Rcpp_DrawLambda_LNRT <- function(RT, zeta, sigma2, mu, sigma) {
    .Call('LNIRT_Rcpp_DrawLambda_LNRT', PACKAGE = 'LNIRT', RT, zeta, sigma2, mu, sigma)
}

#'@export
Rcpp_DrawS_LNIRT <- function(alpha0, beta0, guess0, theta0, Y) {
    .Call('LNIRT_Rcpp_DrawS_LNIRT', PACKAGE = 'LNIRT', alpha0, beta0, guess0, theta0, Y)
}

#'@export
Rcpp_DrawZ_LNIRT <- function(alpha0, beta0, theta0, S, D, eta, PNO) {
    .Call('LNIRT_Rcpp_DrawZ_LNIRT', PACKAGE = 'LNIRT', alpha0, beta0, theta0, S, D, eta, PNO)
}

#'@export
Rcpp_DrawTheta_LNIRT <- function(alpha0, beta0, Z, mu, sigma) {
    .Call('LNIRT_Rcpp_DrawTheta_LNIRT', PACKAGE = 'LNIRT', alpha0, beta0, Z, mu, sigma)
}

#'@export
Rcpp_DrawC_LNIRT <- function(S, Y) {
    .Call('LNIRT_Rcpp_DrawC_LNIRT', PACKAGE = 'LNIRT', S, Y)
}

#'@export
Rcpp_DrawBeta_LNIRT <- function(theta, alpha, Z, mu, sigma) {
    .Call('LNIRT_Rcpp_DrawBeta_LNIRT', PACKAGE = 'LNIRT', theta, alpha, Z, mu, sigma)
}

#'@export
Rcpp_DrawLambda_LNIRT <- function(RT, phi, zeta, sigma2, mu, sigmal) {
    .Call('LNIRT_Rcpp_DrawLambda_LNIRT', PACKAGE = 'LNIRT', RT, phi, zeta, sigma2, mu, sigmal)
}

#'@export
Rcpp_DrawAlpha_LNIRT <- function(theta, beta, Z, mu, sigma) {
    .Call('LNIRT_Rcpp_DrawAlpha_LNIRT', PACKAGE = 'LNIRT', theta, beta, Z, mu, sigma)
}

#'@export
Rcpp_DrawPhi_LNIRT <- function(RT, lambda, zeta, sigma2, mu, sigmal) {
    .Call('LNIRT_Rcpp_DrawPhi_LNIRT', PACKAGE = 'LNIRT', RT, lambda, zeta, sigma2, mu, sigmal)
}

#'@export
Rcpp_SampleS2_LNIRT <- function(RT, zeta, lambda, phi) {
    .Call('LNIRT_Rcpp_SampleS2_LNIRT', PACKAGE = 'LNIRT', RT, zeta, lambda, phi)
}

#'@export
rcpp_hello <- function() {
    .Call('LNIRT_rcpp_hello', PACKAGE = 'LNIRT')
}

