# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@export
Rcpp_DrawS_LNIRT <- function(alpha0, beta0, guess0, theta0, Y) {
    .Call('LNIRT_Rcpp_DrawS_LNIRT', PACKAGE = 'LNIRT', alpha0, beta0, guess0, theta0, Y)
}

#'@export
Rcpp_DrawZ_LNIRT <- function(alpha0, beta0, theta0, S, D, eta, PNO = FALSE) {
    .Call('LNIRT_Rcpp_DrawZ_LNIRT', PACKAGE = 'LNIRT', alpha0, beta0, theta0, S, D, eta, PNO)
}

#'@export
Rcpp_DrawTheta_LNIRT <- function(alpha0, beta0, Z, mu, sigma) {
    .Call('LNIRT_Rcpp_DrawTheta_LNIRT', PACKAGE = 'LNIRT', alpha0, beta0, Z, mu, sigma)
}

#'@export
Rcpp_DrawZeta_LNIRT <- function(RT, phi, lambda, sigma2, mu, sigmaz) {
    .Call('LNIRT_Rcpp_DrawZeta_LNIRT', PACKAGE = 'LNIRT', RT, phi, lambda, sigma2, mu, sigmaz)
}

#'@export
Rcpp_DrawC_LNIRT <- function(S, Y) {
    .Call('LNIRT_Rcpp_DrawC_LNIRT', PACKAGE = 'LNIRT', S, Y)
}

#'@export
rcpp_hello <- function() {
    .Call('LNIRT_rcpp_hello', PACKAGE = 'LNIRT')
}

